<?php

    /**
    *
    * Generated by DezDevTools @ 2015-10-30 21:31:35
    *
    * @author Ivan Gontarenko
    * @licence MIT
    *
    */

    namespace App\Model\Entity;

    use App\Model\Entity\GeneratedEntity\Entity_f2ab5fb218da8b84623f45579aa4ba11;

    class Sources extends Entity_f2ab5fb218da8b84623f45579aa4ba11
    {

    }