<?php

    /**
     *
     * Generated by DezDevTools @ 2015-10-30 21:32:05
     *
     * @author Ivan Gontarenko
     * @licence MIT
     *
    */

    namespace App\Model\Entity\GeneratedEntity;

    use Dez\ORM\Model\Table as OrmEntity;

    class Entity_f2ab5fb218da8b84623f45579aa4ba11 extends OrmEntity {

        static protected $table     = 'sources';
        
        /**
         * @return mixed
         */
        public function getName() {
            return $this->get( 'name' );
        }

        /**
         * @param mixed $name
         * @return $this
         */
        public function setName( $name ) {
            $this->set( 'name', $name );
            return $this;
        }
        
        /**
         * @return mixed
         */
        public function getContent() {
            return $this->get( 'content' );
        }

        /**
         * @param mixed $content
         * @return $this
         */
        public function setContent( $content ) {
            $this->set( 'content', $content );
            return $this;
        }
        
        /**
         * @return mixed
         */
        public function getLanguage() {
            return $this->get( 'language' );
        }

        /**
         * @param mixed $language
         * @return $this
         */
        public function setLanguage( $language ) {
            $this->set( 'language', $language );
            return $this;
        }
        
    }